name: cloudrun-deploy
on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION}}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION_NAME }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI v0.2.0
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.GCP_SA_MAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build a docker image
      run: docker build . -t $IMAGE

    - name: Push the docker image
      run: docker push $IMAGE
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION_NAME }} \
        --image $IMAGE \
        --project $GCP_PROJECT \
        --region $GCP_REGION \
        --platform managed \
        --quiet